twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - MicroServices
    - Spring
    - Kafka
    - ElasticSearch
  welcome-message: Hello Microservices
  enable-mock-tweets: true
  mock-min-tweet-length: 15
  mock-max-tweet-length: 100
  mock-sleep-ms: 10000